projects:
  diveboard:
    schemaPath: amplify/backend/api/diveboard/build/schema.graphql
    includes:
      - schema
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: .
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
